[theme]
primaryColor = "#0066cc"         # Blue for buttons and highlights
backgroundColor = "#030303ff"      # Light grey background
secondaryBackgroundColor = "#0f0e0eff" # Card backgrounds
textColor = "#f2ececff"            # Main text color
font = "sans serif"
